xpander-ai/xpander-sdk

src/core/tools.ts

fix(status-codes): fixes the status code checks

---

src/core/XpanderClient.ts

fix(RDT-1172): local tools

---

src/constants/xpanderClient.ts

feat(RDT-1227): base url

---

test/amazonBedrockProvider.notest.ts
test/langChainProvider.notest.ts
test/nvidiaNimProvider.notest.ts
test/openAIProvider.notest.ts
test/xpanderClient.notest.ts

feat(RDT-1227): updated tests

---

API.md
src/core/Configuration.ts
src/core/XpanderClient.ts
src/core/agents/Agent.ts
src/core/base.ts
src/core/promptGroups/PromptGroupSessionsList.ts
src/core/toolCalls.ts
src/core/tools.ts
src/index.ts
src/llmProviders/amazonBedrock.ts
src/llmProviders/langchain.ts
src/llmProviders/shared/baseOpenAI.ts
src/llmProviders/shared/baseProvider.ts
src/types/tools.ts
test/amazonBedrockProvider.notest.ts
test/langChainProvider.notest.ts
test/nvidiaNimProvider.notest.ts
test/openAIProvider.notest.ts

feat(RDT-1506): data types

---

src/core/agents/Agent.ts

feat(RDT-1697): Added search capabilities for huge API responses

---

API.md
src/core/agents/Agent.ts
src/core/agents/AgentsController.ts
src/core/memory/Memory.ts
src/core/tools.ts
src/types/tools.ts
test/xpanderClient.notest.ts

! feat(agents-v1.0): Fully refactor for multi agents

---

src/core/memory/Memory.ts

feat(agents-v1.0): agents executions

---

src/llmProviders/shared/baseProvider.ts

feat(agents): added advanced filtering options

---

src/core/agents/Agent.ts

fix(agents-v1.0): query params fix

---

API.md
src/core/CacheService.ts
src/core/agents/Agent.ts
src/core/knowledgeBases.ts
src/core/memory/Memory.ts
src/index.ts
src/llmProviders/amazonBedrock.ts
src/llmProviders/friendliAI.ts
src/llmProviders/nvidiaNim.ts
src/llmProviders/ollama.ts
src/llmProviders/openai.ts
src/llmProviders/rtOpenAI.ts
test/no-worker.notest.ts

1. added caching
2. combined memory “select_llm_provider” and “initialize_thread”
3. removed redundant enums
4. performance improvements

feat(RDT-1768): fixes + performance + caching

---

API.md
src/constants/llmProvider.ts
src/core/XpanderClient.ts
src/core/agents/Agent.ts
src/core/executions/Execution.ts
src/core/graphs/GraphItem.ts
src/core/memory/Memory.ts
src/llmProviders/geminiOpenAI.ts
src/llmProviders/index.ts
test/no-worker.gemini.notest.ts

usage: LLMProvider.GEMINI_OPEN_AI

feat(gemini): added google gemini support

---

src/core/agents/Agent.ts

fix(queryparams): arrays in query params fix

---

src/core/agents/Agent.ts
src/core/tools/utils.ts

usually agent controller reports the tool call result
in this case where we have output schema enforcement we need the sdk to handle it

fix(output-schema): add tool result in case of having an output schema. locally VS controller

---

src/core/agents/AgentsController.ts

[RDT-1926] Fix agents.list() URL construction to properly handle organization IDs

---

src/core/agents/AgentsController.ts

fix: properly extract base URL in agents.list() 

---

API.md
src/core/agents/Agent.ts
src/core/agents/AgentsController.ts

fix(agents-crud): list url fix + sync issue

---

API.md
src/core/agents/Agent.ts
src/core/memory/Memory.ts
src/llmProviders/amazonBedrock.ts
test/bedrock-no-worker.notest.ts

fix(bedrock-converse): messages, tool calls and such for amazon bedrock

---

.github/workflows/build.yml
.github/workflows/release.yml
.projen/deps.json
.projenrc.ts
package.json
yarn.lock

feat(node): upgraded rosetta + node

---

API.md
src/core/agents/Agent.ts
src/core/tools/ToolCall.ts
src/llmProviders/shared/baseProvider.ts

fix(tool-calls): local tools improvements

---

src/core/agents/Agent.ts
src/core/utils.ts
test/agentic-interfaces.notest.ts
test/bedrock-no-worker.notest.ts
test/crud.notest.ts
test/delegation.notest.ts
test/graphs.notest.ts
test/local-tools.notest.ts
test/metrics.notest.ts
test/no-worker.gemini.notest.ts
test/no-worker.notest.ts
test/worker.notest.ts

feat(agent-instructions): read agent instructions from file system

---

src/core/agents/Agent.ts

fix(errors): error handling for tool result report

---

.projen/deps.json
.projenrc.ts
API.md
package.json
src/core/agents/Agent.ts
src/core/graphs/Graph.ts
src/core/tools/utils.ts
src/llmProviders/openai.ts
src/llmProviders/shared/baseProvider.ts
src/types/agents.ts
test/agentic-interfaces.notest.ts
test/bedrock-no-worker.notest.ts
test/crud.notest.ts
test/delegation.notest.ts
test/graphs.notest.ts
test/local-tools.notest.ts
test/metrics.notest.ts
test/no-worker.gemini.notest.ts
test/no-worker.notest.ts
test/worker.notest.ts
yarn.lock

feat(mcp): added mcp support

---

API.md
docs/python/Agent.md
docs/python/AgentInstructions.md
docs/python/LLMTokens.md
docs/python/Memory.md
docs/python/README.md
docs/python/Tokens.md
docs/typescript/Agent.md
docs/typescript/AgentInstructions.md
docs/typescript/LLMTokens.md
docs/typescript/Memory.md
docs/typescript/README.md
docs/typescript/Tokens.md
src/core/agents/Agent.ts
src/core/agents/AgentInstructions.ts
src/core/agents/index.ts
src/core/executions/TokensUsage.ts
src/core/memory/Memory.ts
src/core/utils.ts
src/index.ts
src/types/agents.ts

refactor xpander agents instructions to:
role: str[]
goal: str[]
general: str
and to be a class

feat(agent-instructions): refactored agent instructions structure

---

.vscode/launch.json
README.md
docs/BACKEND.md
src/xpander_sdk/modules/backend/AGENTS.md
src/xpander_sdk/modules/backend/README.md
src/xpander_sdk/modules/backend/backend_module.py
src/xpander_sdk/modules/events/decorators/on_task.py
src/xpander_sdk/modules/events/events_module.py
tests/events_tester.py
tests/test_backend_module.py

This PR introduces environment variable support for agent ID retrieval in the Backend module and significantly improves the `@on_task` decorator with expanded documentation and strict validation. It also includes updates to tests and docs for better clarity and reliability.
- **Backend module**:  
- Now supports fetching `agent_id` from the `XPANDER_AGENT_ID` environment variable if not provided directly.
- Improved error messages and validation for argument retrieval.
- **on_task decorator**:  
- Enhanced documentation with detailed usage examples and clearer guidelines.
- Added validation to ensure decorated functions have the correct signature and return type.
- Improved error handling for invalid usage.
- **Documentation**:  
- Updated `README.md`, `BACKEND.md`, and module-specific …

feat(PRO-67): add env var support to Backend module & enhance on_task docs/validation

---

docs/BOOT_SHUTDOWN_HANDLERS.md
docs/EVENTS.md
src/xpander_sdk/__init__.py
src/xpander_sdk/modules/agents/sub_modules/agent.py
src/xpander_sdk/modules/backend/frameworks/agno.py
src/xpander_sdk/modules/events/README.md
src/xpander_sdk/modules/events/decorators/on_boot.py
src/xpander_sdk/modules/events/decorators/on_shutdown.py
src/xpander_sdk/modules/events/events_module.py
tests/events_tester.py
tests/test_boot_shutdown_handlers.py

This pull request introduces lifecycle event management to the xpander.ai SDK, enabling developers to register initialization and cleanup logic using new decorators. The following changes are included:
- **Added `@on_boot` and `@on_shutdown` decorators**  
- Boot handlers execute before event listeners are set up, ideal for initialization tasks (e.g., database connection, config loading).
- Shutdown handlers execute during application termination, ideal for cleanup tasks (e.g., closing resources, saving state).
- Both support async and sync functions, and execute in registration order.
- **Documentation updates**  
- New guide: `docs/BOOT_SHUTDOWN_HANDLERS.md` with detailed usage, best practices, and troubleshooting.
- Updated `docs/EVENTS.md` and …

feat(PRO-76): add lifecycle event decorators for boot and shutdown handlers

---

src/xpander_sdk/modules/backend/backend_module.py
src/xpander_sdk/modules/tasks/sub_modules/task.py

This PR introduces NeMo integration into the backend module, expanding agent runtime management and task execution capabilities. It updates `Backend` with async/sync agent invocation supporting richer context, output formatting, and external task reporting. The changes also extend the task module with async/sync reload methods for improved object refresh.
- Added NeMo integration in backend agent invocation
- Expanded agent runtime features: direct invocation, runtime argument resolution, external task reporting
- Enhanced async/sync APIs for agent and task operations
- Improved docstrings and type hints for clarity
- Added `reload` and `areload` methods to `Task` for object refresh
- `src/xpander_sdk/modules/backend/backend_module.py` (+199/-5)
- …

feat(PRO-183): add NeMo integration and agent runtime enhancements

---

src/xpander_sdk/consts/api_routes.py
src/xpander_sdk/modules/backend/frameworks/agno.py
src/xpander_sdk/modules/tools_repository/sub_modules/tool.py
src/xpander_sdk/modules/tools_repository/tools_repository_module.py
tests/test_tools_repository.py

This PR adds new tools repository methods and expands Agno framework integration.
- New API route for tool invocation.
- Refactored Agno backend: improved agent argument construction, model provider support (OpenAI, Nvidia NIM, Anthropic), tool hooks, and team logic.
- Enhanced Tool class: invocation patterns, schema validation, error handling.
- ToolsRepository: supports async/sync tool loading and invocation, improved function signatures.
- New tests for tool retrieval and invocation by ID.
- "feat(PRO-194): added tools methods"
- "feat(tools): NeMo and Nvidia NIM"
- 566 additions, 159 deletions, 5 files changed.

feat(PRO-194): tools repository & Nvidia NIM & NeMo integration
